### ISSUE TITLE
Proot terminated

### ISSUE THREAD

**Issue by illialoo99** [sp4rkie/debian-on-termux#10]
After `bash enter_deb` i see `proot info: vpid 1: terminated with signal 11`.
How to fix this?

**Comment by sp4rkie** [comment]
the problem must be fixed in `proot`. Please have a look at: 

terminated with signal 11 · Issue #112 https://github.com/proot-me/PRoot/issues/112

**Comment by sp4rkie** [comment]
please report issues with proot directly here:
https://github.com/termux/proot/issues
