### ISSUE TITLE
debian-on-termux is not starting

### ISSUE THREAD

**Issue by LaChirla** [sp4rkie/debian-on-termux#11]
After the installation I did a:
enter_deb
it  gives me a :

proot info: vpid 1: terminated with signal 11

Thanks

**Comment by Atavic** [comment]
See: https://github.com/sp4rkie/debian-on-termux/issues/10#issuecomment-350684409

**Comment by sp4rkie** [comment]
sorry but proot problems are out of scope here. In the meantime there is available a new proot version anyway. Maybe the issue got fixed now. The above error message is not very specific to narrow down the root cause.
