### ISSUE TITLE
How can termux-api features be used inside debian?

### ISSUE THREAD

**Issue by abinashdash17** [sp4rkie/debian-on-termux#14]
I tried mounting the termux's usr to /termuxusr , then running termux-share which fails. How can I use them in debian-chroot environment?

**Comment by abinashdash17** [comment]
I've posted this issue in termux-api issues too as I don't know whether it is a debian-chroot issue or termux-api issue.

**Comment by sp4rkie** [comment]
what exactly do you want to share? Export content from chrooted-env to android or vice versa? Can you give the commandline(s) you issued?

**Comment by abinashdash17** [comment]
What I want to do exactly is to successfully run "termux-share an_image_file.png" inside chrooted debian environment. If it's not possible, then running a single bash script file inside chroot-debian from the host system(i.e termux) and exiting the from the chroot env will be okay too.just like [here](https://stackoverflow.com/questions/8157931/bash-executing-commands-from-within-a-chroot-and-switch-user)

**Comment by sp4rkie** [comment]
how can you run "termux-share" inside chrooted debian environment as the command does not exist there?
If you want to export some files located inside the chrooted debian environment why don't you that from within termux directly? Maybe this way:
termux-share deboot_debian/home/u0_a142/x.png

**Comment by sp4rkie** [comment]
as depicted in the README you run single commands in chrooted environment like so:

    enter_deb -n id
this would just execute 'id' in chrooted environment and drop back to termux environment after this. Please check 'README/ sample usage: debian one-shot command' for another example.

**Comment by abinashdash17** [comment]
Right... That one shot command can get my work done. I forgot to check readme. Anyway thanks for such a beautiful script(debian-on-termux). Thanks to your script, I can enjoy almost all of my favourite debian packages,which are not yet available on termux main repo, on my android.

**Comment by abinashdash17** [comment]
Just found a way to run `termux-share` inside debian chroot(probably inside any chroot).<br />
Here's the link: [How to run termux-share inside chroot](https://github.com/termux/termux-api/issues/140)<br />
P.S - Most of the time oneshot command can get the work done. But if anyone needs to run `termux-share` inside chroot badly, plz have a look at the above link. :D
