### ISSUE TITLE
problem running sshd 

### ISSUE THREAD

**Issue by morgonhed** [sp4rkie/debian-on-termux#15]
I am running Debian 9.4 on termux on a Fire 7 tablet.

Everything works fine, except for running sshd.

I've set up authorized_keys and let let sshd run on port 3333 but I cannot log in from remote.

When I run sshd in debug-mode I can see that it accepts the key, but it then closes the connection reporting "Access denied for user u0_a41 by PAM account configuration".

However all lines in /etc/security/access.conf are commented out.
I have tried to add "+:ALL:ALL" to this file but the problem persists.
I have tried to disable PAM by adding "skip-authentication" to /etc/pam.conf but to no avail.

Running sshd in a pure termux-environment works fine for me, however trying to run it in a Debian-enviroment (which I would like to do) runs into this problem.

Any ideas?

Many thanks!

**Comment by sp4rkie** [comment]
I don't think that sshd will run under faked-root unless you apply a patch
