### ISSUE TITLE
Android oreo seccomp filter prevent packages installation like apt

### ISSUE THREAD

**Issue by wean-irdeh** [sp4rkie/debian-on-termux#19]
See :   https://github.com/corbinlc/GNURootDebian/issues/206

It would be very huge work to solve this issue

**Comment by salvomic** [comment]
I hope to see a workaround! 
In Oreo (my tablet isn't rooted) I cannot got Linux: not GNU Debian nor Linux Deploy (PROOT), only Termux, but limited...

**Comment by freebrowser1** [comment]
And does it work on a rooted Oreo device ?
If yes, that might be a reason to root my Huawei Mate 9.

**Comment by salvomic** [comment]
I don't know, I can't succeed to install root in my Huawei Mediapad M5 :-(

**Comment by thorsummoner** [comment]
I'm wondering if there are any apt-compatible alternatives that work on Oreo, cause not being able to download software that might work because the apt binary uses a forbidden syscall sucks

**Comment by sp4rkie** [comment]
sorry, but all these (in particular GNURootDebian) are not issues related to this project.
