### ISSUE TITLE
Cannot check Release signature;

### ISSUE THREAD

**Issue by TheDoop** [sp4rkie/debian-on-termux#20]
```
patching file functions
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
debian_on_termux.sh: 110: debian_on_termux.sh: cannot create /data/data/com.termux/files/home/deboot_debian/etc/passwd: Directory nonexistent
$
```
  I'm using lineage OS 15.1 Android 8.1 non rooted device

**Comment by PhotonMike** [comment]
I have the same issue on my OnePlus 3 running NitrogenOS (Android 8.1). Also, most PRoot-based Termux-distros break after upgrading (apt upgrade, dnf upgrade, pacman -Syu).

**Comment by projectextremum** [comment]
@PhotonMike can you explain how they break? Pasting some error messages is fine.

Termux provided debootstrap does not have the keyring, you can provide it yourself by wisely unpacking official keyring package or avoiding keyring altogether via suitable options. Latter is risky though.

**Comment by sp4rkie** [comment]
fixed
