### ISSUE TITLE
Questions about use

### ISSUE THREAD

**Issue by Sunr0** [sp4rkie/debian-on-termux#25]
No root privileges can not be used,

 if possible, what should be selected aarch64 architecture?

**Comment by sp4rkie** [comment]
per default termux does not support a rooted device. That's why also in debian-on-termux there is not real 'root' available. 
Probably 'arm64' is the closest one. I don't know if somebody ever tested this. I do not own such a device.

**Comment by Dmole** [comment]
Yes aarch64=arm64 it was just a GNU vs Apple naming inconsistency.

**Comment by Sunr0** [comment]
oh thinks
