### ISSUE TITLE
x86 support?

### ISSUE THREAD

**Issue by cgarz** [sp4rkie/debian-on-termux#3]
Hello. I saw your reference on the sshfs support request for termux.

I got all excited and tried this immediately and only read the readme properly when it broke. Only arm arch's =(

Is x86 support a possibility? 
Or do you have any suggestions of other avenues I could take to get debian or at least sshfs on my Zenfone 2?

Thank you for making this anyway. All the other debian android things are ancient. It's nice to see a fresh one.

**Comment by sp4rkie** [comment]
sorry for the confusion. Opposed to what I wrote there is no such architecture restriction. But architectures not mentioned I did'n test.

Any architecture offered by debian (and suitable for your hardware) probably will work. I will fix the docu.

For `sshfs` at least a rooted device is required. Since otherwise you get `permission denied` when it tries to open `/dev/fuse`. Would be interesting if `sshfs` really works.

**Comment by cgarz** [comment]
Thanks for the reply. I've since read more around termux and debian. I really should stop just diving in head 1st with excitement lol. I hadn't seen the proot method before. Found the link on the debian site and the termux wiki and on the installing Deb 9.2 #1645 termux issue.

I have tested your script again to get the specific error. This is what it spits out at the end:
`patching file functions
CANNOT LINK EXECUTABLE: library "PREFIX=/data/data/com.termux/files/usr" not found
page record for 0xf767708c was not found (block_size=64)
./debian_on_termux.sh: 110: ./debian_on_termux.sh: cannot create /data/data/com.termux/files/home/deboot_debian/etc/passwd: Directory nonexistent
`

I have also tried the method described in post 2 of issue #1645. It seems to complete fine but when I run the start script after fixing the usr/bin/env problem it says:
`mesg: change /dev/pts/1 mode failed: Permission denied`
But then changes the promt to root@localhost as if it may be working.
I was really unsure of testing with apt to see if it had incase it screwed termux's apt thing up with root as I have done in the past. 
I tried anyway. apt said it was using ftp.debian.org streatch as if it really is working. But then the dreaded apt with root termux problem displays its signature message - W: No sandbox user '_apt' on the system, can not drop privileges

I thought I might have to go fix apt again for the 100th time but exiting out and trying apt worked fine. So proot deb kind of works. But it's apt doesnt.

I've also tried loading it with the sudo script but then it says it cant find bash in the location where bash clearly is for termux. Perhaps the shebang fix carries over when it shouldn't?

**Comment by sp4rkie** [comment]
after the message

        patching file functions 
should follow something like

        I: Retrieving InRelease
        I: Retrieving Release 
        I: Retrieving Packages 
        I: Validating Packages 
        I: Resolving dependencies of required packages...
        [...]
you can't see such messages?
if not the first debootstrap stage fails for some reason.
did you use the latest version of `debian_on_termux.sh`?
what is logged to file `$HOME/deboot_debian/debootstrap/debootstrap.log`?
what value did you choose for `ARCHITECTURE` in `debian_on_termux.sh`?

**Comment by cgarz** [comment]
It seems it hasn't made a deboot_debian folder at all.  The only new folder in $HOME is debootstrap-1.0.91 and the only thing with log in the name in that folder is changelog.

I have tested again with the latest version and the results are the same.

The arch specified is i386 and I have also tried i686.

The stdout info I'm getting from this script is this:

> `~$ ./debian_on_termux.sh 
Hit:1 http://termux.net stable InRelease
Reading package lists...
Building dependency tree...
Reading state information...
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists...
Building dependency tree...
Reading state information...
perl is already the newest version (5.26.1).
proot is already the newest version (5.1.106-3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
--2017-10-28 16:01:49--  http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz
Resolving http.debian.net... 130.89.148.14, 5.153.231.4, 128.31.0.62, ...
Connecting to http.debian.net|130.89.148.14|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz [following]
--2017-10-28 16:01:49--  http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz
Resolving cdn-fastly.deb.debian.org... 151.101.0.204, 151.101.64.204, 151.101.128.204, ...
Connecting to cdn-fastly.deb.debian.org|151.101.0.204|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70171 (69K) [application/x-gzip]
Saving to: ‘STDOUT’

-                                 100%[==========================================================>]  68.53K  --.-KB/s    in 0.05s   

2017-10-28 16:01:49 (1.37 MB/s) - written to stdout [70171/70171]

patching file functions
CANNOT LINK EXECUTABLE: library "PREFIX=/data/data/com.termux/files/usr" not found
page record for 0xf771508c was not found (block_size=64)
./debian_on_termux.sh: 110: ./debian_on_termux.sh: cannot create /data/data/com.termux/files/home/deboot_debian/etc/passwd: Directory nonexistent
`

**Comment by sp4rkie** [comment]
very strange. Does your login shell source  a weirdos `.profile`? :-)
What does the command

        termux-chroot echo \\$PATH
output? 
Does

        termux-chroot wget http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz
work?

**Comment by cgarz** [comment]
It may indeed actually lol. I forgot I customized it. This is what's in it:
```
~$ cat .profile
if [ -n "BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
  fi
fi
```
And for .bashrc it's:
```
~$ cat .bashrc 
PS1="\[\033[0;37m\]\[\033[0;32m\]\u@$(getprop net.hostname)\[\033[0;34m\]\w\$\[\033[00m\] "

#eval "`dircolors`"
alias ls='ls --color=auto'
alias ll='ls --color=auto -lshaF'

export TERM=xterm-256color
export HISTSIZE=100000
export HISTFILESIZE=100000
shopt -s histappend
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

shopt -s checkwinsize
```

And your test commands are like so:
```
~$ termux-chroot echo \\$PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```

```
~$ termux-chroot wget http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz--2017-10-28 18:22:47--  http://http.debian.net/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz
Resolving http.debian.net... 149.20.4.15, 5.153.231.4, 130.89.148.14, ...
Connecting to http.debian.net|149.20.4.15|:80... connected.
HTTP request sent, awaiting response... 302 Found 
Location: http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz [following]
--2017-10-28 18:22:48--  http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.91.tar.gz
Resolving cdn-fastly.deb.debian.org... 151.101.0.204, 151.101.64.204, 151.101.128.204, ...
Connecting to cdn-fastly.deb.debian.org|151.101.0.204|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70171 (69K) [application/x-gzip]
Saving to: ‘debootstrap_1.0.91.tar.gz.2’

debootstrap_1.0.91.tar.gz.2       100%[==========================================================>]  68.53K  --.-KB/s    in 0.05s   

2017-10-28 18:22:48 (1.38 MB/s) - ‘debootstrap_1.0.91.tar.gz.2’ saved [70171/70171]
```

```
~$ cd ~/debootstrap-1.0.91/
~/debootstrap-1.0.91$ export DEBOOTSTRAP_DIR=`pwd`
~/debootstrap-1.0.91$ LD_PRELOAD= $PREFIX/bin/proot \
>     -b /system \
>     -b /vendor \
>     -b /data \
>     -b /property_contexts \
>     -b /storage \
>     -b $PREFIX:/usr \
>     -b $PREFIX/bin:/bin \
>     -b $PREFIX/etc:/etc \
>     -b $PREFIX/lib:/lib \
>     -b $PREFIX/share:/share \
>     -b $PREFIX/tmp:/tmp \
>     -b $PREFIX/var:/var \
>     -b /dev \
>     -b /proc \
>     -r $PREFIX/.. \
>     -0 \
>     --link2symlink \
>     sh -x ./debootstrap --foreign --arch=i386 stretch $HOME/deboot_debian http://deb.debian.org/debian
CANNOT LINK EXECUTABLE: library "LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" not found
page record for 0xf76d208c was not found (block_size=64)

```

**Comment by sp4rkie** [comment]
thanks for your testing. I think I now know what the problem was. Could you please test with the new version . And please use either `i386` or `amd64` for architecture since `i686` is not supported.

**Comment by cgarz** [comment]
Oooo yes nice, that got me much further thanks. It did almost everything. I'm assuming creating enter_deb is the last or near last stage?

It ends with:
```
I: Base system installed successfully.                                                                                               
./debian_on_termux.sh: 265: ./debian_on_termux.sh: cannot create /data/data/com.termux/files/home/bin/enter_deb: Permission denied
```
Arch is set as i386.
The access of /data/data/com.termux/files/home is 0700. Is that correct?

**Comment by sp4rkie** [comment]
permissions for $HOME is the same here.

But it appears  that the directory created by

        mkdir -p $HOME/bin
(about line 264) got strange permissions. I've never got such problems here. Could you please show the output of

        ls -l $HOME/bin

**Comment by cgarz** [comment]
Odd. I'm getting permission denied even though I own it.

```
~$ ls -l $HOME/bin
ls: cannot open directory '/data/data/com.termux/files/home/bin': Permission denied
```

```
~$ stat $HOME/bin
  File: /data/data/com.termux/files/home/bin
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 10303h/66307d   Inode: 3498966     Links: 2
Access: (0700/drwx------)  Uid: (10100/ u0_a100)   Gid: (10100/ u0_a100)
Access: 2017-08-27 22:20:51.426004063 +0100
Modify: 2017-08-27 22:20:51.736004065 +0100
Change: 2017-08-27 22:21:42.276004373 +0100
 Birth: -
```

```
~$ whoami
u0_a100
```

**Comment by sp4rkie** [comment]
you created this directory `2017-08-27 `. Owner and access permissions are ok. No clue what there is going on. If you are not allowed to access the directory can you rename (or delete) it? 
Does creating a new `$HOME/bin` work as expected?

**Comment by cgarz** [comment]
I think I have it. I think its the same problem I have when I accidentally use root for apt.

I have moved the bin folder to bin.bak using root.
Then I made a new bin folder.
Then I have copied bin.bak's contents with permissions using rsync -a to the new bin folder.

I am able to see a difference using getfattr.
New nice bin folder:
```
~$ getfattr -d -m ".*" bin
# file: bin
security.selinux="u:object_r:app_data_file:s0:c512,c768"
```
Old troublesome one:
```
~$ getfattr -d -m ".*" bin.bak
# file: bin.bak
security.selinux="u:object_r:app_data_file:s0"
```

**Comment by sp4rkie** [comment]
ok, great! If `bin` now is writable by  the `termux` user you could try to call `debian_on_termux.sh` again. If `deboot_debian` is still in place and unchanged it is sufficient to simply execute `DO_THIRD_STAGE`. I.e to save time set

        DO_FIRST_STAGE=false
        DO_SECOND_STAGE=false
and execute the script again. Should finish quickly and all is done:-)

**Comment by cgarz** [comment]
Ah that would have been much better. I just took the overkill option and deleted everything and started again lol.

That's why the update came later. Had to sit through the full install again because of that lol.

Where should I discuss further things? Like running as root and executing a process within proot debian from say a termux shortcut task?

**Comment by sp4rkie** [comment]
> Where should I discuss further things?

I'm quite new to `termux`. I would skim https://github.com/termux/termux-packages/issues?utf8=%E2%9C%93&q=is%3Aissue%20root for further info.

> running as root and executing a process within proot debian from outside it

You can use `enter_deb` for one shot commands like this:

        enter_deb ls -l

I will try to setup the Android simulator to run  in rooted mode to get some more experiences. I think I can close this issue...

**Comment by cgarz** [comment]
Thank you for all your help. #3 all wrapped up nicely. I shall test sshfs more then post on the sshfs request thread.
