### ISSUE TITLE
is it possible to run termux api commands?

### ISSUE THREAD

**Issue by morgonhed** [sp4rkie/debian-on-termux#32]
Hi,
first of all thanks a lot for your efforts, being able to run a (sort of) debian on my tablet is absolutely fantastic.

What I would like to do is to post notifications from within the debian-environment.
In a pure termux environment I can run "termux-notification" to achieve this, which resides in /data/data/com.termux/files/usr/bin.

I have added "/data/data/com.termux/" as a -p argument to the proot call that starts the debian-environment and the path is now available from within the debian-environment and I can see the programs, but they don't run.

So is there a way to run "termux-notification" from within the debian-environment?

Many thanks!"

**Comment by Dmole** [comment]
Maybe use a shared named pipe to proxy the call?

**Comment by abinashdash17** [comment]
Check this link : [issue on running termux api commands in debian](https://github.com/sp4rkie/debian-on-termux/issues/14)

**Comment by sp4rkie** [comment]
@morgonhed:
did the link from above work for you?

**Comment by projectextremum** [comment]
@sp4rkie issue being that people forget it once they can't get it right. And github doesn't even have a proper notification system. :P
