### ISSUE TITLE
Sources.list problem with debrootstrap.invalid

### ISSUE THREAD

**Issue by mrjpaxton** [sp4rkie/debian-on-termux#34]
I think when the script uses debootstrap to create /etc/apt/sources.list, the URL has a line that says "debootstrap.invalid" instead of using some sane defaults.

Can this be fixed somehow?

If anyone can't reproduce it, I'll post more info.

**Comment by Dmole** [comment]
https://github.com/sp4rkie/debian-on-termux/blob/master/README.md#issues

**Comment by sp4rkie** [comment]
probably a side effect of some other issue not mentioned here. With current version '/etc/apt/sources.list' is setup correctly on my test phones with Android 6.0/ 8.0/ 9.0

        # $HOME/bin/enter_deb cat /etc/apt/sources.list
        deb http://deb.debian.org/debian stable main

please reopen should the problem persist
