### ISSUE TITLE
wishlist: devuan-on-termux

### ISSUE THREAD

**Issue by bolangi** [sp4rkie/debian-on-termux#35]
Hi,

I'm interested in installing Devuan, which is a Debian derivative without systemd, under termux.  Would you be interesting in supporting it?

Cheers,

**Comment by sr-tream** [comment]
Nice idea! Because systemd could work in chroot (and proot)

**Comment by sr-tream** [comment]
Fck! Devuan support only i385 and amd64

**Comment by nartahn** [comment]
It supports arm. https://pkgmaster.devuan.org/devuan/dists/ascii/main/binary-armel/Release

**Comment by projectextremum** [comment]
@sr-team, does the init system has any valuable function in `proot`?

It would be certainly possible tweaking few lines of `debootstrap` but is it going to make any difference?

**Comment by sr-tream** [comment]
@projectextremum classic start services, like `service start nginx`
