### ISSUE TITLE
Error using command ls

### ISSUE THREAD

**Issue by yuyueshihaoren** [sp4rkie/debian-on-termux#40]
bash-4.4# ls
ls: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
bash-4.4#

**Comment by projectextremum** [comment]
`apt-get install pcre3` should work, otherwise use busybox.

```
$ apt-get install busybox-static
$ busybox --install /bin
$ echo "export TERM=screen-256color" >> /etc/profile

Busybox ls won't give all features but essential stuff will work.
