### ISSUE TITLE
Orca screen reader do not support Firefox at all when runing llatest Debian ARM64 bit.

### ISSUE THREAD

**Issue by JanuszChmiel** [sp4rkie/debian-on-termux#41]
Dear specialists,
I would like to express my deepest possible appreciation to The programmers work which author of this script have invested. Script is working perfectly, run smoothly with no crash. And when installing complex desktop environments I do not get bug related to D-BUS socket not found and other sockets related problems.
But because nobody want to help Me even nobody from Orca mailing list, I have one complex question for you.
Why Orca screen reader do not interact with Firefox when running from The installed Debian?
The most sad fact is, that I do not error on The console. Orca simply do not speak at all when Firefox window is on The foreground. Build in Firefox hod keys areworking.
I can run many GTK apps with Orca if developer do not use shared memory, sincethismemory model is not being supported by Android.
I know about one .so library, butit would very probably recode complex C source codes of apps, which arecalling shared memory.
So Ithink, that may be, Firefox can not cooperate with Orca thanks to shared memoryproblem or, may be that when system want to use sockets pair, communication fail.
I believe, that thereis some way to setup system so Firefox will be usable with Orca even on Android and Termux.
Thank you very much for yours help.
With kindness regards.
Janusz Chmiel

**Comment by Dmole** [comment]
Off topic
