### ISSUE TITLE
Apt not installed

### ISSUE THREAD

**Issue by Momiro** [sp4rkie/debian-on-termux#44]
I have just finished installing, and I am trying to set up the OS, but I don't even have apt, it's not in the bin either.

Edit: here is the end of the console log 

I: Unpacking the base system...
W: Failure trying to run:  dpkg --force-overwrite --force-confold --skip-same-version --install /var/cache/apt/archives/adduser_3.115_all.deb /var/cache/apt/archives/libapparmor1_2.11.0-3+deb9u2_arm64.deb /var/cache/apt/archives/libcryptsetup4_2%3a1.7.3-4_arm64.deb /var/cache/apt/archives/libip4tc0_1.6.0+snapshot20161117-6_arm64.deb /var/cache/apt/archives/libkmod2_23-2_arm64.deb /var/cache/apt/archives/libcap2_1%3a2.25-1_arm64.deb /var/cache/apt/archives/libidn11_1.33-1_arm64.deb /var/cache/apt/archives/libseccomp2_2.3.1-2.1+deb9u1_arm64.deb /var/cache/apt/archives/dmsetup_2%3a1.02.137-2_arm64.deb /var/cache/apt/archives/libdevmapper1.02.1_2%3a1.02.137-2_arm64.deb /var/cache/apt/archives/libncurses5_6.0+20161126-1+deb9u2_arm64.deb /var/cache/apt/archives/libprocps6_2%3a3.3.12-3+deb9u1_arm64.deb /var/cache/apt/archives/procps_2%3a3.3.12-3+deb9u1_arm64.deb /var/cache/apt/archives/systemd_232-25+deb9u6_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
update-alternatives: error: no alternatives for editor
info: Trying to set 'debconf/frontend' [select] to 'Editor'
info: Loading answer for 'debconf/frontend'
info: Trying to set 'debconf/priority' [select] to 'low'
info: Loading answer for 'debconf/priority'
info: Trying to set 'locales/locales_to_be_generated' [select] to 'en_US.UTF-8 UTF-8'
info: Loading answer for 'locales/locales_to_be_generated'
info: Trying to set 'locales/default_environment_locale' [select] to 'en_US.UTF-8'
info: Loading answer for 'locales/default_environment_locale'

Current default time zone: 'America/Denver'
Local time is now:      Sun Dec 16 03:23:15 MST 2018.
Universal Time is now:  Sun Dec 16 10:23:15 UTC 2018.

/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 27: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 28: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
/tmp/dot_tmp.sh: 34: /tmp/dot_tmp.sh: apt: not found

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb

$

**Comment by Momiro** [comment]
Here is a paste of the debootstrap.log
https://hastebin.com/lonawoleha.pl

**Comment by chenyulue** [comment]
The same problem

**Comment by WassiliaPL** [comment]
I: Retrieving libxapian30 1.4.3-2+deb9u2
I: Validating libxapian30 1.4.3-2+deb9u2
I: Retrieving liblzma5 5.2.2-1.2+b1
I: Validating liblzma5 5.2.2-1.2+b1
I: Retrieving zlib1g 1:1.2.8.dfsg-5
I: Validating zlib1g 1:1.2.8.dfsg-5
I: Chosen extractor for .deb packages: dpkg-deb
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/deboot_debian, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
debian_on_termux.sh: 237: debian_on_termux.sh: cannot create /data/data/com.termux/files/home/deboot_debian/root/.profile: Directory nonexistent
$

Error during installation process. Think it's the problem.

**Comment by sudomain** [comment]
The install script uses the VERSION variable to determine which debian release to install. It's default is 'stable'. At the time of OP's post, 'stable' meant 'jessie' i.e. Debian 9.
At the time of this writing, 'stable' means 'buster' i.e. Debian 10. Buster seems to have apt installed, but I'm experiencing a certificate issue when trying to apt update or apt install.
I also tested Debian 8 (VERSION=stretch) which has worked the best out of the 3 so far.

**Comment by sp4rkie** [comment]
fixed
