### ISSUE TITLE
add armv8l architecture

### ISSUE THREAD

**Issue by ghistes** [sp4rkie/debian-on-termux#45]
debian_on_termux.sh does not work out of the box on a Fire 10 HD with the error-message "Unsupported architecture armv8l".

However simply adding a line 

armv8l) ARCHITECTURE=armhf ;;

in the case-statement works just fine.

**Comment by Dmole** [comment]
https://github.com/sp4rkie/debian-on-termux/commit/4e6a2ebdfaa3c5a4fe6e574fa44ec15d2135dc1c
