### ISSUE TITLE
Pulseaudio not initializing

### ISSUE THREAD

**Issue by ashuhar455** [sp4rkie/debian-on-termux#47]
Want to stream sound using pulseaudio over TCP but on `pulseaudio -d` it gives error 
` W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [pulseaudio] main.c: Daemon startup failed `

Plz help

**Comment by Dmole** [comment]
https://github.com/sp4rkie/debian-on-termux/blob/master/README.md#issues

**Comment by sp4rkie** [comment]
'-d' is not a valid option. Do you mean '-D'?
If it says 'unless --system is specified' what about specifying it?

        /usr/bin/pulseaudio --disallow-exit --daemonize=no --system --realtime --log-target=journal

starts without complaining
