### ISSUE TITLE
How to copy files between Debian and Android/termux

### ISSUE THREAD

**Issue by iryek219** [sp4rkie/debian-on-termux#51]
Hi,

Termux provides an easy way to share data with Android host by giving access to /storage folder.

Is there any similar method to share data with termux/Android?

**Comment by sp4rkie** [comment]
you can add particular host directories to allow access from within the debian guest system. Simply add these with '-b' Option in 'enter_deb' script.

E.g. to make '/storage/emulated/0' accessible from within debian apply this patch:

        --- /data/data/com.termux/files/home/bin/enter_deb.a    2020-03-04 15:25:59.221529113 +0100
        +++ /data/data/com.termux/files/home/bin/enter_deb      2020-03-04 15:25:56.361529114 +0100
        @@ -39,6 +39,7 @@
         eval $PREFIX/bin/proot \
             -b /dev \
             -b /proc \
        +    -b /storage/emulated/0 \
             -r $HOME/$ROOTFS_TOP_ \
             -w $HOMEDIR_ \
             $CAPS_ \

the bind then goes to '/storage' and is simply accessible by (example):

        root@localhost:~# ls -lisaR /storage | less

        /storage:
        total 24
        659830 8 drwx------.  3 root root 4096 Mar  4 15:28 .
        656360 8 drwxr-xr-x. 18 root root 4096 Mar  4 15:28 ..
        659832 8 drwx------.  3 root root 4096 Mar  4 15:28 emulated

        /storage/emulated:
        total 24
         659832 8 drwx------. 3 root root 4096 Mar  4 15:28 .
         659830 8 drwx------. 3 root root 4096 Mar  4 15:28 ..
        1179970 8 drwxrwx---. 7 root 9997 4096 Mar  1 17:08 0

        /storage/emulated/0:
        total 488
        1179970   8 drwxrwx---. 7 root 9997   4096 Mar  1 17:08 .
         659832   8 drwx------. 3 root root   4096 Mar  4 15:28 ..
        1179801   8 drwxrwx---. 4 root 9997   4096 Feb 26 05:22 Android
        1180794   8 drwxrwx---. 3 root 9997   4096 Feb 28 10:06 DCIM
        1179971   8 drwxrwx---. 2 root 9997   4096 Mar  4 05:42 Download
        1179802   8 drwxrwx---. 2 root 9997   4096 Feb 28 07:35 Ghostracer
        1180070 440 drwxrwx---. 2 root 9997 442368 Mar  4 10:48 GonnyCam
