### ISSUE TITLE
[SOLVED] FATAL: Kernel too old

### ISSUE THREAD

**Issue by nbbm26** [sp4rkie/debian-on-termux#52]
found this on an old droid 4 when running enter_deb. after full setup and running script this was the error mssg.

after doing some research found an option in the proot man pages stating a -k option can spoof a newer kernel as this custom kernel is 3.something

so added line in the proot init 
    -k 4.0 \ #the backslash needed at the end of this line isn't showing in this editor for some reason
as well as 
PREFIX_=/data/data/com.termux/files/usr

then
cd /data/data/com.termux/files/home/bin
and
sh enter_deb

and.....

bash5-0#
!!!!!!!

**Comment by nartahn** [comment]
I have the same problem. Which file(s) exactly have you altered?  I cant find the proot init. I hope it isn't systemd related... I want to convert debian to devuan.

**Comment by nbbm26** [comment]
Yeah, so basically that varies depending on your system.  Usually, most of the installs I tried end up (like in AnLinux with a Fedora build because they mainlined ARM repos) with a start-fedora.sh or something of a kind, which you would start from Termux by doing cd to that directory, then typing ./start-fedora.sh or whatever.  Inside that script there should be a line for the proot command (which you installed with Termux, right?).  Just tack on a new line
\ ##this is the end of the prior bash line in order to add command arguments
-k 4.0 \ ##followed by this line to add this option

But if you're using a homebuilt version without Termux (i.e. <Android 5.0), you kinda have to run proot as it's own command in a terminal emulator of some sort with the option -k 4.0 or build it into a script as above (and put it all on one line without the \ beginning or ending if desired).  In this case,  make sure the home directory and all the other command line stuff needed for proot is sound

https://wiki.debian.org/ChrootOnAndroid

http://manpages.ubuntu.com/manpages/trusty/man1/proot.1.html

Sincerely,
Nbbm26

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nbbm26** [comment]
You can also run this if your install came with a shell script.  This is an expensive system search (max depth 999) so make sure it's recursion starts from the Termux or Debian or Devuan file system base.

find . -maxdepth 999 -type f -exec grep -lnE "proot" '{}' \; -print

**Comment by sp4rkie** [comment]
> found this on an old droid 4 when running enter_deb. after full setup and running script this was the error mssg.

termux itself does not support Android versions <= 5. Please have a look at [FAQ - Termux Wiki](https://wiki.termux.com/wiki/FAQ)

so how can you run debian-on-termux on droid 4 at all?

**Comment by sp4rkie** [comment]
sorry, but the problem reported does not refer to this project
