### ISSUE TITLE
ps -ef impossible

### ISSUE THREAD

**Issue by wbtx** [sp4rkie/debian-on-termux#53]
Hello sir,

ps -ef is impossible inside debian on termux, it returns to try "mount proc /proc -t proc" but its says "/proc : cannot mount proc read-only". How can I fix this problem ? 

sincerely yours

**Comment by Dmole** [comment]
/proc is now mounted with
https://raw.githubusercontent.com/sp4rkie/debian-on-termux/master/debian_on_termux_10.sh

```
grep -a . /proc/[0-9]*/cmdline
/proc/17794/cmdline:/data/data/com.termux/files/usr/bin/bash-l
/proc/18129/cmdline:bashs/debian_on_termux_10.sh
/proc/18130/cmdline:proot-0--link2symlink-r/data/data/com.termux/files/home/debian-testing-w/root-b/dev/-b/sys/-b/proc/-b/data/data/com.termux/files/home/usr/bin/env-iHOME=/rootTERM=xterm-256colorPATH=/bin:/usr/bin:/sbin:/usr/sbin/bin/bash--login
/proc/18132/cmdline:/bin/bash--login
```

Please let us know if if works for you.
Note that unshare -p is not permitted so termux is visible.

**Comment by wbtx** [comment]
Hello sir,

I sent an email directly for you after receiving your message.

Can you give me an example of a small configuration to install debian in termux with debian_on_termux.sh for Android 5.0.1.

sincerely yours

wget -q https://raw.githubusercontent.com/sp4rkie/debian-on-termux/master/debian_on_termux.sh && sh debian_on_termux.sh
======== DO_FIRST_STAGE ========
tar: debootstrap/scripts/artful: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/ascii: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/beowulf: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/bionic: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/bookworm: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/bullseye: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/buster: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/ceres: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/cosmic: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/disco: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/eoan: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/focal: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/jessie: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/jessie-kfreebsd: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/oldoldstable: Cannot change mode to rwx------: No such file or directory
tar: debootstrap/scripts/oldstable: Cannot change mode to rwx------: No such file or directory
tar: Exiting with failure status due to previous errors

termux-info:
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
Updatable packages:
All packages up to date
Android version:
5.0.1
Kernel build information:
Linux localhost 3.4.0-5978264 #1 SMP PREEMPT Wed Nov 16 19:05:34 KST 2016 armv7l Android

**Comment by Dmole** [comment]
rm the folder, and try the _10 script I linked to previously.

**Comment by wbtx** [comment]
Hello sir,I installed termux, wget and then did :wget -q https://raw.githubusercontent.com/sp4rkie/debian-on-termux/master/debian_on_termux_10.sh && sh debian_on_termux_10.shthere were two errors and the installation was stopped :W: Cannot check Release signature; keyring file not available /data/data/com.termux/files/usr/share/keyrings/debian-archive-keyring.gpgandI: Extracting libhogweed5...E: Tried to extract package, but file already exists. Exit...bash-5.0#sincerely yours$ pkg install wgetReading package lists... DoneBuilding dependency tree... DoneThe following additional packages will be installed:  libunistring libuuid pcre2The following NEW packages will be installed:  libunistring libuuid pcre2 wget0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.Need to get 1576 kB of archives.After this operation, 7078 kB of additional disk space will be used.Do you want to continue? [Y/n] yGet:1 https://termux.net stable/main arm libunistring arm 0.9.10-4 [483 kB]Get:2 https://termux.net stable/main arm libuuid arm 1.0.3-4 [9628 B]Get:3 https://termux.net stable/main arm pcre2 arm 10.33-2 [817 kB]Get:4 https://termux.net stable/main arm wget arm 1.20.3-3 [267 kB]Fetched 1576 kB in 2s (626 kB/s)Selecting previously unselected package libunistring.(Reading database ... 3062 files and directories currently installed.)Preparing to unpack .../libunistring_0.9.10-4_arm.deb ...Unpacking libunistring (0.9.10-4) ...Selecting previously unselected package libuuid.Preparing to unpack .../libuuid_1.0.3-4_arm.deb ...Unpacking libuuid (1.0.3-4) ...Selecting previously unselected package pcre2.Preparing to unpack .../archives/pcre2_10.33-2_arm.deb ...Unpacking pcre2 (10.33-2) ...Setting up wget (1.20.3-3) ...$ wget -q https://raw.githubusercontent.com/sp4rkie/debian-on-termux/master/debian_on_termux_10.sh && sh debian_on_termux_10.shReading package lists... DoneBuilding dependency treeReading state information... Donewget is already the newest version (1.20.3-3).The following additional packages will be installed:  libtalloc perlThe following NEW packages will be installed:  debootstrap libtalloc perl proot0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.Need to get 13.9 MB of archives.After this operation, 60.4 MB of additional disk space will be used.Get:1 https://termux.net stable/main arm libtalloc arm 2.1.14-4 [33.5 kB]Get:2 https://termux.net stable/main arm proot arm 5.1.107-23 [66.6 kB]Get:3 https://termux.net stable/main arm perl arm 5.30.0-2 [13.7 MB]Get:4 https://termux.net stable/main all debootstrap all 1.0.116-1 [30.0 kB]Fetched 13.9 MB in 17s (803 kB/s)Selecting previously unselected package libtalloc.(Reading database ... 3331 files and directories currently installed.)Preparing to unpack .../libtalloc_2.1.14-4_arm.deb ...Unpacking libtalloc (2.1.14-4) ...Selecting previously unselected package proot.Preparing to unpack .../proot_5.1.107-23_arm.deb ...Unpacking proot (5.1.107-23) ...Selecting previously unselected package perl.Preparing to unpack .../archives/perl_5.30.0-2_arm.deb ...Unpacking perl (5.30.0-2) ...Selecting previously unselected package debootstrap.Preparing to unpack .../debootstrap_1.0.116-1_all.deb ...Unpacking debootstrap (1.0.116-1) ...Setting up perl (5.30.0-2) ...Setting up libtalloc (2.1.14-4) ...Setting up proot (5.1.107-23) ...Setting up debootstrap (1.0.116-1) ...W: Cannot check Release signature; keyring file not available /data/data/com.termux/files/usr/share/keyrings/debian-archive-keyring.gpgI: Retrieving InReleaseI: Retrieving PackagesI: Validating PackagesI: Resolving dependencies of required packages...I: Resolving dependencies of base packages...I: Checking component main on http://ftp.debian.org/debian...I: Retrieving libacl1 2.2.53-8I: Validating libacl1 2.2.53-8I: Retrieving adduser 3.118I: Validating adduser 3.118I: Retrieving apt 2.1.6I: Validating apt 2.1.6I: Retrieving libapt-pkg6.0 2.1.6I: Validating libapt-pkg6.0 2.1.6I: Retrieving libattr1 1:2.4.48-5I: Validating libattr1 1:2.4.48-5I: Retrieving libaudit-common 1:2.8.5-3I: Validating libaudit-common 1:2.8.5-3I: Retrieving libaudit1 1:2.8.5-3+b1I: Validating libaudit1 1:2.8.5-3+b1I: Retrieving base-files 11I: Validating base-files 11I: Retrieving base-passwd 3.5.47I: Validating base-passwd 3.5.47I: Retrieving bash 5.0-6I: Validating bash 5.0-6I: Retrieving libbz2-1.0 1.0.8-3I: Validating libbz2-1.0 1.0.8-3I: Retrieving libdebconfclient0 0.252I: Validating libdebconfclient0 0.252I: Retrieving coreutils 8.30-3I: Validating coreutils 8.30-3I: Retrieving dash 0.5.10.2-7I: Validating dash 0.5.10.2-7I: Retrieving libdb5.3 5.3.28+dfsg1-0.6I: Validating libdb5.3 5.3.28+dfsg1-0.6I: Retrieving debconf 1.5.74I: Validating debconf 1.5.74I: Retrieving debian-archive-keyring 2019.1I: Validating debian-archive-keyring 2019.1I: Retrieving debianutils 4.9.1I: Validating debianutils 4.9.1I: Retrieving diffutils 1:3.7-3I: Validating diffutils 1:3.7-3I: Retrieving dpkg 1.19.7I: Validating dpkg 1.19.7I: Retrieving e2fsprogs 1.45.6-1I: Validating e2fsprogs 1.45.6-1I: Retrieving libcom-err2 1.45.6-1I: Validating libcom-err2 1.45.6-1I: Retrieving libext2fs2 1.45.6-1I: Validating libext2fs2 1.45.6-1I: Retrieving libss2 1.45.6-1I: Validating libss2 1.45.6-1I: Retrieving logsave 1.45.6-1I: Validating logsave 1.45.6-1I: Retrieving findutils 4.7.0-1I: Validating findutils 4.7.0-1I: Retrieving gcc-10-base 10.1.0-3I: Validating gcc-10-base 10.1.0-3I: Retrieving libgcc-s1 10.1.0-3I: Validating libgcc-s1 10.1.0-3I: Retrieving libstdc++6 10.1.0-3I: Validating libstdc++6 10.1.0-3I: Retrieving gcc-9-base 9.3.0-13I: Validating gcc-9-base 9.3.0-13I: Retrieving libc-bin 2.30-8I: Validating libc-bin 2.30-8I: Retrieving libc6 2.30-8I: Validating libc6 2.30-8I: Retrieving libgmp10 2:6.2.0+dfsg-4I: Validating libgmp10 2:6.2.0+dfsg-4I: Retrieving gpgv 2.2.20-1I: Validating gpgv 2.2.20-1I: Retrieving libgnutls30 3.6.14-2I: Validating libgnutls30 3.6.14-2I: Retrieving grep 3.4-1I: Validating grep 3.4-1I: Retrieving gzip 1.10-2I: Validating gzip 1.10-2I: Retrieving hostname 3.23I: Validating hostname 3.23I: Retrieving init-system-helpers 1.57I: Validating init-system-helpers 1.57I: Retrieving libcap-ng0 0.7.9-2.2I: Validating libcap-ng0 0.7.9-2.2I: Retrieving libffi7 3.3-4I: Validating libffi7 3.3-4I: Retrieving libgcrypt20 1.8.5-5I: Validating libgcrypt20 1.8.5-5I: Retrieving libgpg-error0 1.38-1I: Validating libgpg-error0 1.38-1I: Retrieving libidn2-0 2.3.0-1I: Validating libidn2-0 2.3.0-1I: Retrieving libseccomp2 2.4.3-1+b1I: Validating libseccomp2 2.4.3-1+b1I: Retrieving libselinux1 3.0-1+b3I: Validating libselinux1 3.0-1+b3I: Retrieving libsemanage-common 3.0-1I: Validating libsemanage-common 3.0-1I: Retrieving libsemanage1 3.0-1+b3I: Validating libsemanage1 3.0-1+b3I: Retrieving libsepol1 3.0-1I: Validating libsepol1 3.0-1I: Retrieving libtasn1-6 4.16.0-2I: Validating libtasn1-6 4.16.0-2I: Retrieving libunistring2 0.9.10-4I: Validating libunistring2 0.9.10-4I: Retrieving libcrypt1 1:4.4.16-1I: Validating libcrypt1 1:4.4.16-1I: Retrieving libzstd1 1.4.5+dfsg-2I: Validating libzstd1 1.4.5+dfsg-2I: Retrieving lsb-base 11.1.0I: Validating lsb-base 11.1.0I: Retrieving liblz4-1 1.9.2-2I: Validating liblz4-1 1.9.2-2I: Retrieving mawk 1.3.4.20200120-2I: Validating mawk 1.3.4.20200120-2I: Retrieving libtinfo6 6.2-1I: Validating libtinfo6 6.2-1I: Retrieving ncurses-base 6.2-1I: Validating ncurses-base 6.2-1I: Retrieving ncurses-bin 6.2-1I: Validating ncurses-bin 6.2-1I: Retrieving libhogweed5 3.5.1+really3.5.1-2I: Validating libhogweed5 3.5.1+really3.5.1-2I: Retrieving libnettle7 3.5.1+really3.5.1-2I: Validating libnettle7 3.5.1+really3.5.1-2I: Retrieving libp11-kit0 0.23.20-1I: Validating libp11-kit0 0.23.20-1I: Retrieving libpam-modules 1.3.1-5I: Validating libpam-modules 1.3.1-5I: Retrieving libpam-modules-bin 1.3.1-5I: Validating libpam-modules-bin 1.3.1-5I: Retrieving libpam-runtime 1.3.1-5I: Validating libpam-runtime 1.3.1-5I: Retrieving libpam0g 1.3.1-5I: Validating libpam0g 1.3.1-5I: Retrieving libpcre2-8-0 10.3I: Validating libpcre2-8-0 10.3I: Retrieving libpcre3 2:8.39-12+b1I: Validating libpcre3 2:8.39-12+b1I: Retrieving perl-base 5.30.3-4I: Validating perl-base 5.30.3-4I: Retrieving sed 4.7-1I: Validating sed 4.7-1I: Retrieving login 1:4.8.1-1I: Validating login 1:4.8.1-1I: Retrieving passwd 1:4.8.1-1I: Validating passwd 1:4.8.1-1I: Retrieving libsystemd0 245.6-1I: Validating libsystemd0 245.6-1I: Retrieving libudev1 245.6-1I: Validating libudev1 245.6-1I: Retrieving sysvinit-utils 2.96-3I: Validating sysvinit-utils 2.96-3I: Retrieving tar 1.30+dfsg-7I: Validating tar 1.30+dfsg-7I: Retrieving tzdata 2020a-1I: Validating tzdata 2020a-1I: Retrieving bsdutils 1:2.35.2-2I: Validating bsdutils 1:2.35.2-2I: Retrieving libblkid1 2.35.2-2I: Validating libblkid1 2.35.2-2I: Retrieving libmount1 2.35.2-2I: Validating libmount1 2.35.2-2I: Retrieving libsmartcols1 2.35.2-2I: Validating libsmartcols1 2.35.2-2I: Retrieving libuuid1 2.35.2-2I: Validating libuuid1 2.35.2-2I: Retrieving mount 2.35.2-2I: Validating mount 2.35.2-2I: Retrieving util-linux 2.35.2-2I: Validating util-linux 2.35.2-2I: Retrieving liblzma5 5.2.4-1+b1I: Validating liblzma5 5.2.4-1+b1I: Retrieving zlib1g 1:1.2.11.dfsg-2I: Validating zlib1g 1:1.2.11.dfsg-2I: Chosen extractor for .deb packages: dpkg-debI: Extracting libacl1...I: Extracting adduser...I: Extracting apt...I: Extracting libapt-pkg6.0...I: Extracting libattr1...I: Extracting libaudit-common...I: Extracting libaudit1...I: Extracting base-files...I: Extracting base-passwd...I: Extracting bash...I: Extracting libbz2-1.0...I: Extracting libdebconfclient0...I: Extracting coreutils...I: Extracting dash...I: Extracting libdb5.3...I: Extracting debconf...I: Extracting debian-archive-keyring...I: Extracting debianutils...I: Extracting diffutils...I: Extracting dpkg...I: Extracting e2fsprogs...I: Extracting libcom-err2...I: Extracting libext2fs2...I: Extracting libss2...I: Extracting logsave...I: Extracting findutils...I: Extracting gcc-10-base...I: Extracting libgcc-s1...I: Extracting libstdc++6...I: Extracting gcc-9-base...I: Extracting libc-bin...I: Extracting libc6...I: Extracting libgmp10...I: Extracting gpgv...I: Extracting libgnutls30...I: Extracting grep...I: Extracting gzip...I: Extracting hostname...I: Extracting init-system-helpers...I: Extracting libcap-ng0...I: Extracting libffi7...I: Extracting libgcrypt20...I: Extracting libgpg-error0...I: Extracting libidn2-0...I: Extracting libseccomp2...I: Extracting libselinux1...I: Extracting libsemanage-common...I: Extracting libsemanage1...I: Extracting libsepol1...I: Extracting libtasn1-6...I: Extracting libunistring2...I: Extracting libcrypt1...I: Extracting libzstd1...I: Extracting lsb-base...I: Extracting liblz4-1...I: Extracting mawk...I: Extracting libtinfo6...I: Extracting ncurses-base...I: Extracting ncurses-bin...I: Extracting libhogweed5...E: Tried to extract package, but file already exists. Exit...bash-5.0#Le 17 juin 2020 14:28, Tim <notifications@github.com> a écrit :
rm the folder, and try the _10 script I linked to previously.

**Comment by Dmole** [comment]
> I: Extracting libhogweed5...
> E: Tried to extract package, but file already exists. 

Odd.
