### ISSUE TITLE
I want permission to modify your file

### ISSUE THREAD

**Issue by KitsuneIDK** [sp4rkie/debian-on-termux#56]
I want create a repository with all available Linux distro working for Termux and I want add Debian so I came ask if you give me permission to modify and reupload your proot script, please

**Comment by Dmole** [comment]
1) Do with it as you wish, because it's now GPL2.1
2) I advise using Git Submodules and sending distros Pull Requests instead of forking all the code.
3) Maybe you can get all the distros to use a common lib to reduce code duplication.

**Comment by KitsuneIDK** [comment]
thanks
