### ISSUE TITLE
Files in /proc missing?

### ISSUE THREAD

**Issue by simonbelmont** [sp4rkie/debian-on-termux#57]
Hello,
not really experienced Termux user here.

i just installed Debian on Termux and some programs aren't really working, it always seems to have to do with /proc.
It looks like there are files missing, when I compare it to the "real" /proc directory on my Android.
Should they look the same?

I found other posts about this, one referring to start with enter_deb -p.
But the -p option is not available.

I also have seen the link with the proot_5.1.106-3_arm.deb.gz file.
But it does not fit my architecture.
 
I would love to make this work!

When I start htop with tsu in Termux for example, everything looks fine. I just don't have access with the Debian installation.

Thanks for helping out a noob....

**Comment by sp4rkie** [comment]
there are some restrictions (e.g. accessing /proc) with non-rooted Android installations. Termux does a hard work to overcome these with  specially tailored patches. 

As we install pure Debian packages we do not have such options. As a result some vanilla Debian commands simply don't work.
