### ISSUE TITLE
HUAWEI Mate 10 lite and debian running problem

### ISSUE THREAD

**Issue by JanuszChmiel** [sp4rkie/debian-on-termux#58]
Dear MR specialist,
I have tried to install Debian by using yours script, because yours environment support dbus and Linux sockets at The professional level. So even Orca screen reader can be perfectly used with GTK apps. Unfortunately, I AM helpless to install Debian by using yours script to my mobile phone model. May be, that it is because it uses Android 7.0 and some required specific Termux packages have problem with so new Android, so Debian can not start. Here is error.

grep: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
grep: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
grep: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb

As A result, Debian can not be started.
How could I help you to debug this complex programmers issue?

**Comment by JanuszChmiel** [comment]
I have compared The problem by using my other Android device Lenovo TAB 3 8 with Android 6.0. It uses 64 Bit CPU but 32 Bit Android to save memory. It is known strategy of many device manufacturers. But I could install Debian without problems. No error, locale have been correctly changed. And Debian can be used no error while loading shared library. So I Am thinking about The cause of my problem why it is incompatible with Huavei Mate 10 lite..
How could I get all messages which have been produced by The script from its start till The error which have stopped The process?
How could i start yours script so all textual output which will be produced by The processes, all text outputs could be saved in some text format file?
So it is really Android version related problem. 
Scripts routines are perfect.
Any advice will be very welcomed.

**Comment by JanuszChmiel** [comment]
Here is The cvause of my problem.
I: Extracting libpam-runtime...
E: Tried to extract package, but file already exists. Exit...
grep: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
grep: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

So here is The problem.
I: Extracting libpam-runtime...
E: Tried to extract package, but file already exists. Exit...
I have analysed whole log while installing.

**Comment by JanuszChmiel** [comment]
And here is complete log while installing Debian. May be, that this bigger protocol will help.
[debian_install.log](https://github.com/sp4rkie/debian-on-termux/files/3911444/debian_install.log)

**Comment by sp4rkie** [comment]
does this still happen with the current version?

**Comment by JanuszChmiel** [comment]
Fortunately core programmers of Proot have created work around. This was problem of Huavei 10 mate lite file system partial case insensitivity. So it was not yours error. So thanks to Proot work around, it work perfectly for now and you can close this thread.

**Comment by sp4rkie** [comment]
great!
