### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by derek1906** [sp4rkie/debian-on-termux#6]
While executing the bash script, I encountered this:

Connecting to cdn-fastly.deb.debian.org|151.101.0.204|:80... connected.
HTTP request sent, awaiting response... 404 Not Found

**Comment by derek1906** [comment]
### Update

Applying https://github.com/sp4rkie/debian-on-termux/pull/4/commits/855a9d8 fixed the problem.

**Comment by sp4rkie** [comment]
thanks for the report, patch is applied.
