### ISSUE TITLE
Please add language localisation support to yours script

### ISSUE THREAD

**Issue by JanuszChmiel** [sp4rkie/debian-on-termux#61]
SdRausty have made special routine, which can install specific language locale to The system. So all environment variables are correctly set. And even console apps messages are in specified language. Bash shell display prompts in The specified language.
Would be possible to allow users of this script to specify language which will be used as A target system? So locales will be compiled according to The language settings?

**Comment by sp4rkie** [comment]
where can I find SdRausty's "special routine"?

**Comment by JanuszChmiel** [comment]
It is possible to find it inside his ArchLinux script. Inside setup script
for Arch Linux.

https://github.com/SDRausty/termux-archlinux

**Comment by sp4rkie** [comment]
ok, I will have a look at it. Unfortunately there currently are some more important things to fix...

**Comment by Dmole** [comment]
Specifically
```
L="$(getprop ro.product.locale)"
#en-US
```
But note that
"You might want to use the default en_US locale because some software doesn't play nice when locale's set to something else" from https://wiki.debian.org/Locale
so we should likely not do this by default.
