### ISSUE TITLE
problem with proot

### ISSUE THREAD

**Issue by ghistes** [sp4rkie/debian-on-termux#63]
Hi,

I am trying to install debian on termux on my Moto G6 Play and get this error with the current version:

======== DO_SECOND_STAGE ========
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/debian, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

Before running the script I have removed any directories from previous runs, and set VERSION to "testing" and ROOTFS_TOP to "debian".

**Comment by sp4rkie** [comment]
thanks for reporting this. 
the problem:  the signing key for 'testing' release could not be found.
