### ISSUE TITLE
Error Installation on Android 10

### ISSUE THREAD

**Issue by JSilaban** [sp4rkie/debian-on-termux#64]
here the log file for error installation on  my device
[https://del.dog/erfaberyco](https://del.dog/erfaberyco)

**Comment by sp4rkie** [comment]
could you please provide the contents of

        $HOME/deboot_debian/debootstrap/debootstrap.log

**Comment by JSilaban** [comment]
`$ $HOME/deboot_debian/debootstrap/debootstrap.log
bash: /data/data/com.termux/files/home/deboot_debian/debootstrap/debootstrap.log: No such file or directory
$ ls
debian_on_termux.sh  debootstrap  storage
$`

idk why no such folder for $HOME/deboot_debian/..
i follow the right instruction in README.md

**Comment by sp4rkie** [comment]
@Dmole:
could we please make the output of debootstrap visible again?

your commit https://github.com/sp4rkie/debian-on-termux/commit/7071815c55818cd8b0af5c0b1ff5346a4d8054d5#diff-b64542f0a9a06c5dcb5e5d4cd7cf6dc8

unfortunately makes it impossible to diagnose issues like the above

**Comment by JSilaban** [comment]
So, what should i do to make it alive on my android 10 termux? Any script or anything to make it possible? thanks

**Comment by Dmole** [comment]
@sp4rkie please try this;
https://github.com/sp4rkie/debian-on-termux/commit/7a849e1b97f16e33754c6f1265fe3c9a9d2a8c13#diff-b64542f0a9a06c5dcb5e5d4cd7cf6dc8

**Comment by JSilaban** [comment]
here's the log [https://del.dog/apybilosam](https://del.dog/apybilosam)

**Comment by Dmole** [comment]
@JSilaban the log files in the diff are
~/debian-on-termux_debootstrap.log
and
~/debian-on-termux_debootstrap_stage2.log
(though you would only have the first)

**Comment by JSilaban** [comment]
@sp4rkie 
here the debian-on-termux_debootstrap.log

**Comment by sp4rkie** [comment]
sorry, I don't know what proot wants to say with

        proot error: execve("/home/debootstrap/debootstrap"): No such file or directory

I tried to simulate on Android 9 but without success. Must be a specific problem to Android 10.

**Comment by sp4rkie** [comment]
after all this issue is a duplicate to  #62

**Comment by JSilaban** [comment]
~  /data/data/com.termux/files/usr/bin/proot -b /system -b /vendor -b /data -b /data/data/com.termux/files/usr/bin:/bin -b /data/data/com.termux/files/usr/etc:/etc -b /data/data/com.termux/files/usr/lib:/lib -b /data/data/com.termux/files/usr/share:/share -b /data/data/com.termux/files/usr/tmp:/tmp -b /data/data/com.termux/files/usr/var:/var -b /dev -b /proc -r /data/data/com.termux/files/usr/.. -0 --link2symlink ./debootstrap --keyring=/data/data/com.termux/files/home/debian-release-10.gpg --foreign --arch=arm64 stable /data/data/com.termux/files/home/deboot_debian                                              proot error: './debootstrap' is not a regular file            fatal error: see `proot --help`.

**Comment by sp4rkie** [comment]
what version of 'debian_on_termux.sh' do you use?

I read 

        --keyring=/data/data/com.termux/files/home/debian-release-10.gpg

in your comment above. This is 

        -keyring="$PREFIX/etc/apt/trusted.gpg"

in recent versions.

**Comment by Dmole** [comment]
@sp4rkie I think he just copied that from the older linked issue.

**Comment by JSilaban** [comment]
it says 
> proot error: './debootstrap' is not a regular file 

what should i do? sorry cause im confused with symlink steps
