### ISSUE TITLE
The question for entering choice by typing number should be made after pressing Enter key

### ISSUE THREAD

**Issue by JanuszChmiel** [sp4rkie/debian-on-termux#65]
I have found out, that script code do not wait. User must press The number after several seconds in other case, Script will continue and will do The updates.
Could you made standard input so user would had to press number followed by pressing Enter key please?
I will give yours script The chance. You have recoded it. Script do not show every Debootstrap action such as extracntion file name ETC. 
I will also write you The guide how to setup Pulseaudio sound server in Debian so it will send sound chunks to The Simple protocol Player. It will work and sighted users who do not use speech synthesis will be happy. Because for standard operations, which are being performed by sighted users The sound feetback and responsiveness time will be satisfied.
Also no memory allocation crashes should be available. My uide would improve sound support for yours script too.

**Comment by sp4rkie** [comment]
could you please provide more data for diagnosis? A logfile or anything?
