### ISSUE TITLE
every time i try apt install it gives me this error

### ISSUE THREAD

**Issue by javierechevarria** [sp4rkie/debian-on-termux#66]
You are using the editor-based debconf frontend to configure your
# system. See the end of this document for detailed instructions.
#####################################################################

# This package may install new CA (Certificate Authority) certificates
# when upgrading. You may want to check such new CA certificates and
# select only certificates that you trust.
#
#  - yes: new CA certificates will be trusted and installed;
#  - no : new CA certificates will not be installed by default;
#  - ask: prompt for each new CA certificate.
#
# (Choices: yes, no, ask)
# Trust new certificates from certificate authorities?
ca-certificates/trust_new_crts="yes"

#####################################################################
# The editor-based debconf frontend presents you with one or more text
# files to edit. This is one such text file. If you are familiar with
# standard unix configuration files, this file will look familiar to
# you -- it contains comments interspersed with configuration items.
# Edit the file, changing any items as necessary, and then save it and
# exit. At that point, debconf will read the edited file, and use the
# values you entered to configure the system.

**Comment by sp4rkie** [comment]
this is no error. Instead it want's you to confirm your choice. You must edit the contents according to your demands and save+exit the editor.

**Comment by javierechevarria** [comment]
How?  Won't let me out or edit anything
When I press Ctrl + C I get out but it doesn't install anything

**Comment by sp4rkie** [comment]
To exit with saving changes made:

1. Press \<Escape>.
    (You must be in insert or append mode if not, just start typing on a blank line to enter that mode)

 2. Press : \<colon>  
    The cursor should reappear at the lower left corner of the screen beside a colon prompt. The colon indicates that what follows is a Vim command

 3. Enter the following:

                     wq
    Type “wq” , the “w” indicates that the file should be written, or saved which will overwrite existing file and the “q” indicates that vim should quit, or exit
 
4. Then press \<Enter>.
    This will quit the editor, and write all changes you have made; all changes to the document will be saved.
