### ISSUE TITLE
How to install on external sdcard in android 10 ? i have root if needed

### ISSUE THREAD

**Issue by abasgames** [sp4rkie/debian-on-termux#71]

**Comment by sp4rkie** [comment]
> Apps don't have filesystem level write access to external SD card except those using SAF APIs. Quote from official documentation, Termux doesn't have support for SAF:

    Why does Termux have read-only access to the external SD card?

    On recent Android versions, the write access to the external SD card is done over Storage Access Framework. It is not possible to provide it's API to the command line programs.

[applications - How do I access `$HOME/storage` outside of Termux (with a file explorer)? - Android Enthusiasts Stack Exchange](https://android.stackexchange.com/questions/218354/how-do-i-access-home-storage-outside-of-termux-with-a-file-explorer/218374#218374)
