### ISSUE TITLE
Debian 11 (bullseye) support?

### ISSUE THREAD

**Issue by mystery-z** [sp4rkie/debian-on-termux#81]
Let's say I wanted Debian 11 and not Debian 10 (whatever the reason may be, that is not important, yes I know the changes are not very significant).  

The way I see it, if I'm able to get Debian 10 on termux, getting Debian 11 shouldn't be all that difficult. 

What scripts / parts of the scripts would I have to modify in order to get and install Debian 11 instead? 

Thanks~

**Comment by Dmole** [comment]
The default distribution is "testing" which is currently codenamed "bookworm" and will someday be version "12" 
https://github.com/sp4rkie/debian-on-termux/blob/master/debian_on_termux_10.sh#L4
