### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ghost** [sp4rkie/debian-on-termux#82]
Hi guys,

how do I remove the System that got installed by executing the Code '  wget -q https://raw.githubusercontent.com/sp4rkie/debian-on-termux/master/debian_on_termux_10.sh && sh debian_on_termux_10.sh' .
Thanks for help. 

Geetings 

Yannik

**Comment by Dmole** [comment]
```
rm -fr ~/debian-*
```

**Comment by ghost** [comment]
> 

Thanks
